### ISSUE TITLE
Label placement issue

### ISSUE THREAD

**Issue by ramiy** [bitterendio/acf-field-type-json#2]
In the **Field Group** when you change **Label placement** from **Top aligned** to **Left aligned**:

![Screenshot 2020-05-05 16 48 17](https://user-images.githubusercontent.com/576623/81073886-f14ef400-8ef0-11ea-94d1-16333aa70f7d.png)

The field inside the post doesn't really displays the label. Ace editor takes over the entire area (label + input), it is displayed in full-width.

**Comment by ramiy** [comment]
@rozklad ?

**Comment by rozklad** [comment]
thanks for reminder, i will look into this

**Comment by rozklad** [comment]
This issue is fixed in 1.0.1 - https://github.com/bitterendio/acf-field-type-json/releases/tag/1.0.1
